Repository reactjs/az.reactjs.org, pull requests merged in 2020-02, with the labels that each got.

#174 Translate Overview of Concurrent Mode UI Patterns
  content/docs/concurrent-mode-patterns.md
Labels: awaiting review +1

#175 Translate Concurrent Mode Adoption
  content/docs/concurrent-mode-adoption.md
  content/docs/nav.yml
Labels: awaiting review +1

#176 Translate Concurrent Mode Reference
  content/docs/concurrent-mode-reference.md
Labels: awaiting review +1, new page

#177 Translate Community Pages
  content/community/articles.md
  content/community/conferences.md
  content/community/courses.md
  content/community/examples.md
  content/community/external-resources.md
  content/community/meetups.md
  content/community/podcasts.md
  content/community/support.md
  content/community/videos.md
Labels: awaiting review +1, new page

#179 Translate Team Page
  content/community/team.md
Labels: new page, self review

#178 Translate Concurrent Mode Intro
  content/docs/concurrent-mode-intro.md
Labels: awaiting review +1, new page
