Repository reactjs/az.reactjs.org, pull requests merged in 2020-01, with the labels that each got.

#161 Several typos and spelling. Suggest to increase readability
  content/docs/accessibility.md
  content/docs/addons-shallow-renderer.md
  content/docs/addons-test-utils.md
  content/docs/cdn-links.md
  content/docs/code-splitting.md
  content/docs/composition-vs-inheritance.md
  content/docs/context.md
  content/docs/create-a-new-react-app.md
  content/docs/error-boundaries.md
  content/docs/error-decoder.md
  content/docs/faq-ajax.md
  content/docs/faq-structure.md
  content/docs/faq-versioning.md
  content/docs/forwarding-refs.md
  content/docs/getting-started.md
  content/docs/hello-world.md
  content/docs/higher-order-components.md
  content/docs/hooks-custom.md
  content/docs/hooks-effect.md
  content/docs/hooks-faq.md
  content/docs/hooks-intro.md
  content/docs/hooks-overview.md
  content/docs/hooks-reference.md
  content/docs/hooks-state.md
  content/docs/integrating-with-other-libraries.md
  content/docs/jsx-in-depth.md
  content/docs/lifting-state-up.md
  content/docs/lists-and-keys.md
  content/docs/optimizing-performance.md
  content/docs/react-without-es6.md
  content/docs/reference-dom-elements.md
  content/docs/reference-events.md
  content/docs/reference-glossary.md
  content/docs/reference-react-component.md
  content/docs/reference-react-dom.md
  content/docs/reference-react.md
  content/docs/refs-and-the-dom.md
  content/docs/release-channels.md
  content/docs/rendering-elements.md
  content/docs/static-type-checking.md
  content/docs/strict-mode.md
  content/docs/testing-environments.md
  content/docs/testing-recipes.md
  content/docs/thinking-in-react.md
  content/docs/uncontrolled-components.md
  content/home/examples/a-simple-component.md
  content/home/examples/a-stateful-component.md
  content/tutorial/nav.yml
  content/tutorial/tutorial.md
  content/warnings/dont-call-proptypes.md
  glossary.md
Labels: fix translation

#162 Translate Community Resources links and Code of Conduct
  content/community/nav.yml
  src/components/LayoutFooter/Footer.js
Labels: Other

#160 Translate Code Overview
  content/docs/how-to-contribute.md
Labels: awaiting review +1, new page

#166 Translate Codebase Overview
  content/docs/codebase-overview.md
Labels: awaiting review +1

#168 Translate Implementation Notes
  content/docs/implementation-notes.md
  content/docs/nav.yml
Labels: awaiting review +1

#169 Translate Design Principles
  content/docs/design-principles.md
Labels: awaiting review +1

#171 Translate Data Fetching with Suspense
  content/docs/concurrent-mode-suspense.md
Labels: awaiting review +1
